name: CI
on:
  pull_request:
    branches:
      - main

jobs:
  format:
    name: Check files format
    runs-on: [self-hosted, linux, arm64]

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup node
        uses: actions/setup-node@v6
        with:
          node-version: 24
          package-manager-cache: false

      - name: Install dependencies
        run: pnpm install

      - name: Run format command
        run: pnpm format:check

  lint:
    name: Check code lint
    runs-on: [self-hosted, linux, arm64]

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup node
        uses: actions/setup-node@v6
        with:
          node-version: 24
          package-manager-cache: false

      - name: Install dependencies
        run: pnpm install

      - name: Run lint command
        run: pnpm lint:check

  types:
    name: Check types
    runs-on: [self-hosted, linux, arm64]

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup node
        uses: actions/setup-node@v6
        with:
          node-version: 24
          package-manager-cache: false

      - name: Install dependencies
        run: pnpm install

      - name: Run types command
        run: pnpm types:check
